[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_uniswap_v2 = "uni89rwTPZo2AV5jWCv5Jx4GNDWAqc54BePQKcttmUa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/naidu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-amm.ts tests/initialize-pool.ts tests/deposit-liquidity.ts"
